server:
  port: 8081

logging:
  level:
    root: info
    web: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  http:
    log-request-details: true

yueqi:
  security:
    oauth2:
      clients[0]:
        clientId: yueqi
        clientSecret: yueqisecret
      clients[1]:
        clientId: test
        clientSecret: test
